OBJ_OF_INTEREST = [
    ['sink'],
    ['microwave'],
    ['bottle'],
    ['oven'],
    ['refrigerator'],
    ['plant'],
    ['toilet'],
    ['clock'],
    ['bag'],
    ['vase'],
    ['telephone'],
    ['backpack'],
    ['laptop'],
    ['bed'],
    ['book'],
    ['suitcase'],
    ['bicycle'],
    ['clothes'],
    ['shoes'],
    ['shower'],
    ['bathtub'],
    ['plate'],
    ['pillar'],
    ['lamp'],
    ['kettle'],
    ['table', 'desk', 'coffee table', 'side table', 'couch table', 'stand', 'nightstand', 'tv stand'],
    ['chair', 'armchair', 'dining chair', 'desk chair', 'stool'],
    ['couch', 'sofa'],
    ['kitchen cabinet', 'bath cabinet', 'showcase', 'wardrobe', 'cupboard'],
    ['pillow', 'cushion'],
    ['curtain', 'shower curtain'],
    ['tv', 'monitor']
]